project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "⁠⁠Spotify Audio Features Across Generations"
  author:
    - Chaitya Shah (cs4621)
    - Adityaram Komaraneni (ak5480)
  repo-url: https://github.com/adityaram-2003/Spotify-Analytics
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    # - results.qmd
    # - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


